# Generated by Django 5.0 on 2024-01-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maxapp', '0002_post_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
