# Generated by Django 5.0 on 2024-01-31 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maxapp', '0003_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
    ]
