# Generated by Django 5.0 on 2024-02-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maxapp', '0004_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.ImageField(upload_to='documents/')),
            ],
        ),
    ]
